FROM us-docker.pkg.dev/deeplearning-platform-release/gcr.io/tf2-cu123.2-17.py310

WORKDIR /app

COPY src/training/seg-training.py .
COPY src/common/preprocessing_utils.py .

RUN pip install google-cloud-aiplatform[cloud_profiler] SimpleITK opencv-python-headless

CMD ["python", "seg-training.py"]